Total Planned Units = SUM(OperationsPerformanceDaily[planned_units])
Total Actual Units = SUM(OperationsPerformanceDaily[actual_units])
Total Downtime Minutes = SUM(OperationsPerformanceDaily[downtime_minutes])
Total Scrap Units = SUM(OperationsPerformanceDaily[scrap_units])
Total Labor Hours = SUM(OperationsPerformanceDaily[labor_hours])
Total Orders = COUNTROWS(OrderServiceLevels)
Total Revenue = SUM(OrderServiceLevels[order_value_usd])
Total Delayed Orders = CALCULATE(COUNTROWS(OrderServiceLevels), OrderServiceLevels[shipped_on_time] = 0)
Total Perfect Orders = CALCULATE(COUNTROWS(OrderServiceLevels), OrderServiceLevels[perfect_order_flag] = 1)
Throughput Attainment % = DIVIDE([Total Actual Units], [Total Planned Units], 0)
Availability % = 1 - DIVIDE([Total Downtime Minutes], SUM(OperationsPerformanceDaily[available_minutes]), 0)
First Pass Yield % = 1 - DIVIDE([Total Scrap Units], [Total Actual Units], 0)
On-Time Service % = DIVIDE(CALCULATE(COUNTROWS(OrderServiceLevels), OrderServiceLevels[shipped_on_time] = 1), [Total Orders], 0)
Perfect Order % = DIVIDE([Total Perfect Orders], [Total Orders], 0)
Productivity Units per Hour = DIVIDE([Total Actual Units], [Total Labor Hours], 0)
Incident Count = COUNTROWS(QualityIncidents)
Critical Incident Count = CALCULATE(COUNTROWS(QualityIncidents), QualityIncidents[severity] IN {"high", "critical"})
Revenue At Risk = CALCULATE(SUM(OrderServiceLevels[order_value_usd]), OrderServiceLevels[shipped_on_time] = 0)
Expedite Share % = DIVIDE(CALCULATE(COUNTROWS(OrderServiceLevels), OrderServiceLevels[expedite_flag] = 1), [Total Orders], 0)
Network Score = AVERAGE(SitePerformanceScorecard[composite_score])
